 - name: date
   hosts: vm
   become: true
   gather_facts: true
 
   tasks: 
      - name: find the date
        command: date
        register: date_output
      
      - name: show date
        debug:
          var: date_output.stdout 

      - name: dispay resolve.conf
        command: cat /etc/resolv.conf
        register: resolve_output

      - name: show resove content
        debug:
          var: resolve_output.stdout

      - name: copy file
        copy:
          src: /tmp/test_kvm
          dest: /opt/
          mode: '0777'
        register: copy_file
 
      - name: show file
        debug:
            var: copy_file.stdout

  
